<?php

    /* common */

    define('ZERO_OF_1_PAGES', '{0} of {1} pages');
    define('ZERO_1_OF_2_ICONS', '{0} - {1} of {2} icons');
    define('ADD_NEW_ITEM', 'Add New Item');
    define('ADD_NEW_SNIPPET', 'Add New Snippet');
    define('ALERT_STYLE', 'Alert style');
    define('ALERT_TEXT', 'Alert text');
    define('ALT_TEXT', 'Alt text');
    define('APPEND', 'Append');
    define('BADGE_TEXT', 'Badge text');
    define('BLOCKS_WILL_BE_STACKED_ON_XS_DEVICES', 'Blocks will be stacked on xs devices (smartphones)');
    define('BLOCKS_WILL_BE_STACKED_ON_XS_SMALL_DEVICES', 'Blocks will be stacked on xs &amp; small devices (smartphones &amp; small tablets)');
    define('BLOCKS_WILL_BE_STACKED_ON_XS_SMALL_MEDIUM_DEVICES', 'Blocks will be stacked on xs, small &amp; medium devices (smartphones &amp; tablets)');
    define('BLOCKS_WILL_NEVER_BE_STACKED', 'Blocks will never be stacked');
    define('BREAKPOINT', 'Breakpoint');
    define('BROWSE', 'Browse');
    define('BUTTON_SIZE', 'Button size');
    define('BUTTON_STYLE', 'Button style');
    define('CANCEL', 'Cancel');
    define('CELLS', 'Cells');
    define('CENTER', 'CENTER');
    define('CHOOSE_SNIPPET_TO_EDIT', 'Please Choose a snippet to edit');
    define('CHOOSE_SNIPPET_TO_DELETE', 'Please Choose a snippet to delete');
    define('CLOSE_BUTTON', 'CLOSE BUTTON');
    define('CODE', 'Code');
    define('COLOR', 'Color');
    define('COLS', 'Cols');
    define('CONTENT', 'Content');
    define('CURRENT', 'Current');
    define('CUSTOM', 'Custom');
    define('DELETE_CONST', 'Delete');
    define('DELETE_THIS_ITEM', 'Delete this item');
    define('DISABLED', 'Disabled');
    define('DISABLED_ELEMENTS_WILL_NOT_BE_EDITABLE_IN_TINYMCE_EDITOR', 'Disabled elements will not be editable in tinymce editor');
    define('DISMISSABLE', 'Dismissable');
    define('DRAG_DROP_ELEMENTS_TO_PREVIEW', 'Drag &amp; Drop Elements to Preview');
    define('DROP_ELEMENTS_HERE', 'Drop Elements Here');
    define('EDIT', 'Edit');
    define('FOOTER', 'FOOTER');
    define('FOOTER_CONTENT', 'Footer content');
    define('HEADING', 'HEADING');
    define('HEADING_CONTENT', 'Heading content');
    define('HEIGHT', 'Height');
    define('HORIZONTAL_HEADER', 'Horizontal header');
    define('HTML_AUTHORIZED', 'HTML authorized');
    define('ICON', 'Icon');
    define('ICON_SIZE', 'Icon size');
    define('IMAGE', 'Image');
    define('IMAGE_STYLE', 'Image style');
    define('ITEMS', 'Items');
    define('LABEL_STYLE', 'Label style');
    define('LABEL_TEXT', 'Label text');
    define('LINK', 'Link');
    define('MAIN_CONTENT', 'Main content');
    define('MY_FANTASTIC_BUTTON', 'My Fantastic Button');
    define('NEW_CONST', 'New');
    define('NEW_ITEM', 'New Item');
    define('NEXT', 'Next');
    define('NO', 'NO');
    define('NO_CLOSE_BUTTON', 'NO CLOSE BUTTON');
    define('NO_FOOTER', 'NO FOOTER');
    define('NO_HEADING', 'NO HEADING');
    define('NO_IMAGE_SELECTED', 'No image selected');
    define('NO_SNIPPET_TO_DISPLAY', 'No Snippet to Display');
    define('OK', 'OK');
    define('OTHERS', 'Others');
    define('PANEL_CONTENT', 'Panel content');
    define('PANEL_STYLE', 'Panel style');
    define('PANEL_TITLE', 'Panel title');
    define('PHP_FORBIDDEN', 'Php scripts are forbidden');
    define('PLEASE_CHOOSE_AN_IMAGE', 'Please choose an image file');
    define('PLEASE_END_EDIT', 'Please end edit before validate');
    define('POSITION', 'Position');
    define('PREPEND', 'Prepend');
    define('PREVIEW', 'Preview');
    define('PREVIOUS', 'Previous');
    define('PUSH_TO_THE_SIDES', 'PUSH TO THE SIDES');
    define('ROWS_COLS', 'Rows/cols');
    define('RESPONSIVE', 'Responsive');
    define('ROW_COL_EDITION_IS_DISABLED_FOR_EDITED_TABLES', 'Row/col edition is disabled for edited tables.<br>You can easily add/remove rows &amp; cols directly in tinymce.');
    define('SCRIPT_FORBIDDEN', 'Script tags are forbidden');
    define('SECTIONS', 'Sections');
    define('SIZE', 'Size');
    define('SNIPPET_ADDED', 'Snippet has been added');
    define('SNIPPET_DELETED', 'Snippet has been deleted');
    define('SNIPPET_UPDATED', 'Snippet has been updated');
    define('SNIPPETS', 'Snippets');
    define('STRUCTURE', 'Structure');
    define('STYLE', 'Style');
    define('TAG', 'Tag');
    define('TEXT', 'Text');
    define('TIPS_TEMPLATE', 'Tips using templates with tinyMce');
    define('TIPS_TEMPLATE_CONTENT', '<p>Toggle <code>View -> Show Blocks</code> and <code>View -> Visual Aids</code> to show/hide blocks.</p><p><strong>Add new content before deleting placeholder</strong> content to avoid destroying cols.</p>');
    define('TITLE', 'Title');
    define('TITLE_MUST_MATCH', 'Le titre ne doit contenir que des caractères alphanumériques, tirets et espaces (maximum 150 caractères).');
    define('VALUE', 'Value');
    define('VERTICAL_HEADER', 'Vertical header');
    define('WIDTH', 'Width');
    define('WRONG_DATA', 'Wrong data');
    define('YES', 'YES');
    define('YOUR_TEXT', 'Your text');
